### PR TITLE
Improvements while recording quickstarts

### PR DESCRIPTION
**Pull request by phantomjinx**

### CODE REVIEW

**Comment by shawkins** [comment]
So at worst you would see "Error from server: imagestreams "redhat-openjdk18-openshift" already exists" if it already exists.

Should we consider just pulling/installing the entire xpaas image stream json?

**Comment by phantomjinx** [comment]
@shawkins 

Output if creating artifacts for the first time:

> Creating artifacts from komodo-image-streams.json ...
> imagestream "komodo" created
> imagestream "redhat-openjdk18-openshift" created
>
>
> Creating artifacts from beetle-image-streams.json ...
> imagestream "beetle" created
>
>
> Creating artifacts from data-access-service.json ...
> template "data-access-service" created

Output if replacing artifacts:

> Deleting is/redhat-openjdk18-openshift ... 
> imagestream "redhat-openjdk18-openshift" deleted
> 
> Deleting is/komodo ... 
> imagestream "komodo" deleted
>
> Creating artifacts from komodo-image-streams.json ...
> imagestream "komodo" created
> imagestream "redhat-openjdk18-openshift" created
>
> Deleting is/beetle ... 
> imagestream "beetle" deleted
>
> Creating artifacts from beetle-image-streams.json ...
> imagestream "beetle" created
> 
> Deleting template/data-access-service ... 
> template "data-access-service" deleted
>
> Creating artifacts from data-access-service.json ...
> template "data-access-service" created

**Comment by phantomjinx** [comment]
@shawkins 

> Should we consider just pulling/installing the entire xpaas image stream json?

Have considered that but decided that it just doesn't seem necessary (quite a lot of stuff in there). The redhat-jdk 1.2 image is currently the dependency for the published images and has to be there. However, in the cdk installation of OS its already there so its only in vanilla installs, such as minishift and docker, that it is required.

**Comment by shawkins** [comment]
LGTM

**Pull request merged**
